def raise_exception():
    raise ValueError("This is a value error")
